import './js/main.js'

import './default-styles/main.css'
import './wireframes/index.css'
// import './designs/design1/index.css'
// import './designs/design2/index.css'
// import './designs/design3/index.css'
// import './designs/design4/index.css'
import './images/logo.jpg'
import './images/map.jpg'
import './images/cover-design1.jpg'
import './images/about-design1.jpg'
import './images/map-design1.jpg'
import './images/service1-design1.jpg'
import './images/service2-design1.jpg'
import './images/service3-design1.jpg'
import './images/service4-design1.jpg'
import './images/project1-design1.jpg'
import './images/project2-design1.jpg'
import './images/placeholder.png'
